<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="lidar_x_offset" value="0.038471"/>  
    <xacro:property name="lidar_z_offset" value="0.0838"/>


    <joint name = "laser_joint" type = "fixed">
        <parent link = "base_link"/>
        <child link="laser_frame"/>
        <origin xyz="${lidar_x_offset} 0 ${lidar_z_offset - 0.0171}" rpy="0 0 ${pi}"/>
    </joint>

    <link name = "laser_frame">
        <visual>
            <origin rpy="0 0 ${pi}" xyz="0 0 0.0171"/>
            <geometry>
                <mesh filename="package://astro_sim/meshes/ASTRO_LidarAssembly.stl" scale="0.001 0.001 0.001"/>
            </geometry>
            <material name="dark_gray"/>
        </visual>

        <collision>
            <origin rpy="0 0 ${pi}" xyz="0 0 0.0171"/>
            <geometry>
                <mesh filename="package://astro_sim/meshes/ASTRO_LidarAssembly.stl" scale="0.001 0.001 0.001"/>
            </geometry>
        </collision>

        <inertial>
            <origin xyz = "0 0 0" rpy = "0 0 0"/>
            <mass value = "0.26"/>
            <inertia ixx="0.0" ixy="0.0" ixz="0.0" iyy="0.0" iyz="0.0" izz="0.0"/>
        </inertial>
    </link>




</robot>