<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >
    
    <xacro:include filename="materials.xacro"/>
    

    <xacro:property name="ground_clearance" value="0.0146"/>
    <xacro:property name="wheel_radius" value="0.0360"/>
    <xacro:property name="wheel_separation" value="0.306"/>
    <xacro:property name="wheel_thickness" value="0.0160"/>

    <link name="base_footprint"/>

    <joint name="base_link_joint" type="fixed">
        <parent link="base_footprint"/>
        <child  link="base_link"/>
        <origin xyz="0 0 ${wheel_radius}"/>
    </joint>

    <link name="base_link"/>

    <joint name = "chasis_joint" type = "fixed">
        <parent link = "base_link"/>
        <child link = "chasis_link"/>
        <origin xyz = "0 0 0"/>
    </joint>

    <link name = "chasis_link">
        <visual>
            <origin rpy = "0 0 0" xyz = "0 0 0"/>
            <geometry>
                <mesh filename="package://astro_sim/meshes/ASTRO_Chassis.stl" scale="0.001 0.001 0.001"/>
            </geometry>
            <material name="dark_gray"/>
        </visual>
        <collision>
            <origin rpy = "0 0 0" xyz = "0 0 0"/>
            <geometry>
                <mesh filename="package://astro_sim/meshes/ASTRO_Chassis.stl" scale="0.001 0.001 0.001"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz = "0.0125 0 0.0146" rpy = "0 0 0"/>
            <mass value = "4.03"/>
            <inertia ixx="0.04056665167" ixy="0.0" ixz="0.0" iyy="0.03789879167" iyz="0.0" izz="0.07361265167"/>
        </inertial>
    </link>

    <joint name="left_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="left_wheel"/>
        <origin xyz="0 ${wheel_separation/2} 0" rpy="-${pi/2} 0 0"/>
        <axis xyz="0 0 1"/>
    </joint>

    <link name="left_wheel">
        <visual>
            <geometry>
                <cylinder length="${wheel_thickness}" radius="${wheel_radius}" />
            </geometry>
            <material name="gray"/>
        </visual>

        <collision>
            <geometry>
                <cylinder length="${wheel_thickness}" radius="${wheel_radius}" />
            </geometry>
        </collision>
        <inertial>
            <origin xyz = "0 0 0" rpy = "0 0 0"/>
            <mass value = "0.07"/>
            <inertia ixx="0.0000241733" ixy="0.0" ixz="0.0" iyy="0.0000241733" iyz="0.0" izz="0.00004536"/>
        </inertial>
    </link>

    <joint name="right_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="right_wheel"/>
        <origin xyz="0 -${wheel_separation/2} 0" rpy="${pi/2} 0 0"/>
        <axis xyz="0 0 -1"/>
    </joint>

    <link name="right_wheel">
        <visual>
            <geometry>
                <cylinder length="${wheel_thickness}" radius="${wheel_radius}" />
            </geometry>
            <material name="gray"/>
        </visual>

        <collision>
            <geometry>
                <cylinder length="${wheel_thickness}" radius="${wheel_radius}" />
            </geometry>
        </collision>

        <inertial>
            <origin xyz = "0 0 0" rpy = "0 0 0"/>
            <mass value = "0.07"/>
            <inertia ixx="0.0000241733" ixy="0.0" ixz="0.0" iyy="0.0000241733" iyz="0.0" izz="0.00004536"/>
        </inertial>

    </link>

    <joint name = "fl_caster_wheel_joint" type = "fixed">
        <parent link = "base_footprint"/>
        <child link = "fl_caster_wheel"/>
        <origin xyz="0.096 0.0965 ${ground_clearance}" rpy="0 0 0"/>
    </joint>

    <link name="fl_caster_wheel">
        <visual>
            <geometry>
                <sphere radius="${ground_clearance}"/>
            </geometry>
            <material name="white"/>
        </visual>

        <collision>
            <geometry>
                <sphere radius="${ground_clearance}"/>
            </geometry>
        </collision>

        <inertial>
            <origin xyz = "0 0 0" rpy = "0 0 0"/>
            <mass value = "0.063"/>
            <inertia ixx="0.000005371632" ixy="0.0" ixz="0.0" iyy="0.000005371632" iyz="0.0" izz="0.000005371632"/>
        </inertial>
    </link>

    <joint name="fr_caster_wheel_joint" type="fixed">
        <parent link="base_footprint"/>
        <child link ="fr_caster_wheel"/>
        <origin xyz="0.096 -0.0965 ${ground_clearance}" rpy="0 0 0"/>
    </joint>

    <link name="fr_caster_wheel">
        <visual>
            <geometry>
                <sphere radius="${ground_clearance}"/>
            </geometry>
            <material name="white"/>
        </visual>

        <collision>
            <geometry>
                <sphere radius="${ground_clearance}"/>
            </geometry>
        </collision>

        <inertial>
            <origin xyz = "0 0 0" rpy = "0 0 0"/>
            <mass value = "0.063"/>
            <inertia ixx="0.000005371632" ixy="0.0" ixz="0.0" iyy="0.000005371632" iyz="0.0" izz="0.000005371632"/>
        </inertial>
    </link>

    <joint name = "bl_caster_wheel_joint" type = "fixed">
        <parent link = "base_footprint"/>
        <child link = "bl_caster_wheel"/>
        <origin xyz="-0.092 0.1265 ${ground_clearance}" rpy="0 0 0"/>
    </joint>

    <link name="bl_caster_wheel">
        <visual>
            <geometry>
                <sphere radius="${ground_clearance}"/>
            </geometry>
            <material name="white"/>
        </visual>

        <collision>
            <geometry>
                <sphere radius="${ground_clearance}"/>
            </geometry>
        </collision>

        <inertial>
            <origin xyz = "0 0 0" rpy = "0 0 0"/>
            <mass value = "0.063"/>
            <inertia ixx="0.000005371632" ixy="0.0" ixz="0.0" iyy="0.000005371632" iyz="0.0" izz="0.000005371632"/>
        </inertial>
    </link>
    
    <joint name = "br_caster_wheel_joint" type = "fixed">
        <parent link = "base_footprint"/>
        <child link = "br_caster_wheel"/>
        <origin xyz="-0.092 -0.1265 ${ground_clearance}" rpy="0 0 0"/>
    </joint>

    <link name="br_caster_wheel">
        <visual>
            <geometry>
                <sphere radius="${ground_clearance}"/>
            </geometry>
            <material name="white"/>
        </visual>

        <collision>
            <geometry>
                <sphere radius="${ground_clearance}"/>
            </geometry>
        </collision>

        <inertial>
            <origin xyz = "0 0 0" rpy = "0 0 0"/>
            <mass value = "0.063"/>
            <inertia ixx="0.000005371632" ixy="0.0" ixz="0.0" iyy="0.000005371632" iyz="0.0" izz="0.000005371632"/>
        </inertial>
    </link>

</robot>    